version: 0.2

phases:
  pre_build:
    commands:
      - "set -e"
      - "echo Logging in to ECR..."
      - "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
      - "SHORT_SHA=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c1-7)"
      - "IMAGE_TAG=git-${SHORT_SHA}-${CODEBUILD_BUILD_NUMBER}"
      - "IMAGE_URI=${ECR_REPO_URI}:${IMAGE_TAG}"
      - "BUILD_IMAGE=${BASE_IMAGES_REPO_URI}:eclipse-temurin-25-jdk"
      - "RUNTIME_IMAGE=${BASE_IMAGES_REPO_URI}:eclipse-temurin-25-jre"
      - "echo IMAGE_URI=${IMAGE_URI}"
      - "echo BUILD_IMAGE=${BUILD_IMAGE}"
      - "echo RUNTIME_IMAGE=${RUNTIME_IMAGE}"
      - "echo Setting up CodeArtifact..."
      - "echo CODEARTIFACT_DOMAIN_OWNER=${CODEARTIFACT_DOMAIN_OWNER}"
      - "echo CODEARTIFACT_DOMAIN=${CODEARTIFACT_DOMAIN}"
      - "echo CODEARTIFACT_REPO=${CODEARTIFACT_REPO}"
      - "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $CODEARTIFACT_DOMAIN \
          --domain-owner $CODEARTIFACT_DOMAIN_OWNER \
          --query authorizationToken \
          --output text)"
      - "echo CODEARTIFACT_AUTH_TOKEN length: ${#CODEARTIFACT_AUTH_TOKEN}"
      - "CODEARTIFACT_ENDPOINT=$(aws codeartifact get-repository-endpoint \
          --domain $CODEARTIFACT_DOMAIN \
          --domain-owner $CODEARTIFACT_DOMAIN_OWNER \
          --repository $CODEARTIFACT_REPO \
          --format maven \
          --query repositoryEndpoint \
          --output text)"
      - "echo CODEARTIFACT_ENDPOINT=${CODEARTIFACT_ENDPOINT}"
      - "export CODEARTIFACT_AUTH_TOKEN CODEARTIFACT_ENDPOINT"
      - "echo Publishing openapi-dtos..."
      - "docker run \
          -e CODEARTIFACT_AUTH_TOKEN \
          -e CODEARTIFACT_ENDPOINT
          -v $CODEBUILD_SRC_DIR:/workspace \
          -w /workspace \
          ${BUILD_IMAGE} \
          ./gradlew :openapi-dtos:publish"

  build:
    commands:
      - "echo Building image..."
      - "VERSION=${IMAGE_TAG}"
      - "echo VERSION=${VERSION}"
      - "docker build \
          --build-arg VERSION=${VERSION} \
          --build-arg BUILD_IMAGE=${BUILD_IMAGE} \
          --build-arg RUNTIME_IMAGE=${RUNTIME_IMAGE} \
          --build-arg CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN} \
          --build-arg CODEARTIFACT_ENDPOINT=${CODEARTIFACT_ENDPOINT} \
          -t ${IMAGE_URI} ."

  post_build:
    commands:
      - "echo Pushing image..."
      - "docker push ${IMAGE_URI}"
      - "echo ${IMAGE_TAG} > imagetag.txt"
      - "echo Done."

artifacts:
  files:
    - imagetag.txt
